blank_issues_enabled: false
contact_links:
  - name: Commercial license
    url: https://triplemoongoddess.com/clean-vibe/license
    about: Purchase a commercial license for use in for-profit organizations
  - name: Questions
    url: mailto:lisa@triplemoongoddess.com
    about: General questions about clean-vibe
